"""case_group_id default null

Revision ID: 291e1c0979d7
Revises: 3f5aa85514ba
Create Date: 2021-01-14 19:59:49.454548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291e1c0979d7'
down_revision = '3f5aa85514ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
