"""add update time delete

Revision ID: 2ee1f1539f6b
Revises: 40dbe4d70183
Create Date: 2021-01-12 14:50:11.399876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee1f1539f6b'
down_revision = '40dbe4d70183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_project', sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'))
    op.add_column('auto_project', sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'))
    op.add_column('auto_project', sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_project', 'update_time')
    op.drop_column('auto_project', 'is_delete')
    op.drop_column('auto_project', 'create_time')
    # ### end Alembic commands ###
