"""test_plan_job test_plan_job_detail

Revision ID: 36f4b004bd1c
Revises: fe8ae9435b50
Create Date: 2021-02-05 16:54:05.708745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36f4b004bd1c'
down_revision = 'fe8ae9435b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_test_plan', 'test_plan_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_test_plan', sa.Column('test_plan_state', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
