"""job_detail add api_group_id 

Revision ID: 37a984012f2c
Revises: 86e415988e95
Create Date: 2021-02-05 17:41:22.976312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37a984012f2c'
down_revision = '86e415988e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_test_plan_job_detail', sa.Column('api_group_id', sa.Integer(), nullable=True))
    op.add_column('auto_test_plan_job_detail', sa.Column('api_group_result', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('auto_test_plan_job_detail', 'api_result')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_test_plan_job_detail', sa.Column('api_result', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('auto_test_plan_job_detail', 'api_group_result')
    op.drop_column('auto_test_plan_job_detail', 'api_group_id')
    # ### end Alembic commands ###
