"""add base&&base_group(add base.class&&fix Integer)

Revision ID: 3f5aa85514ba
Revises: 71985eb06cba
Create Date: 2021-01-14 15:07:39.744954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5aa85514ba'
down_revision = '71985eb06cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_base_api_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('case_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('request_body', sa.VARCHAR(length=128), nullable=True),
    sa.Column('asert_case', sa.VARCHAR(length=128), nullable=True),
    sa.Column('data_out', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_base_api_group_id'), 'auto_base_api_group', ['id'], unique=False)
    op.create_table('auto_base_api',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('api_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('api_url', sa.VARCHAR(length=128), nullable=True),
    sa.Column('api_request_method', sa.VARCHAR(length=128), nullable=True),
    sa.Column('api_content_type', sa.VARCHAR(length=128), nullable=True),
    sa.Column('api_case_group_id', sa.Integer(), nullable=True),
    sa.Column('is_enable', sa.Integer(), nullable=True, comment='0=未启用,1=已启用'),
    sa.ForeignKeyConstraint(['api_case_group_id'], ['auto_base_api_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_name'),
    sa.UniqueConstraint('api_url')
    )
    op.create_index(op.f('ix_auto_base_api_id'), 'auto_base_api', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_base_api_id'), table_name='auto_base_api')
    op.drop_table('auto_base_api')
    op.drop_index(op.f('ix_auto_base_api_group_id'), table_name='auto_base_api_group')
    op.drop_table('auto_base_api_group')
    # ### end Alembic commands ###
