"""add hahahahahahahat.

Revision ID: 40dbe4d70183
Revises: 7abce4911c5c
Create Date: 2021-01-11 19:05:02.494650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40dbe4d70183'
down_revision = '7abce4911c5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_project', sa.Column('project_user', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_project', 'project_user')
    # ### end Alembic commands ###
