"""add base&&base_group

Revision ID: 71985eb06cba
Revises: 2ee1f1539f6b
Create Date: 2021-01-14 14:21:26.895642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71985eb06cba'
down_revision = '2ee1f1539f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
