"""fix test_plan_job test_plan_job_detail

Revision ID: 86e415988e95
Revises: aa48ec131db1
Create Date: 2021-02-05 17:12:02.281926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e415988e95'
down_revision = 'aa48ec131db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_test_plan_job', sa.Column('fail_count', sa.Integer(), nullable=True))
    op.add_column('auto_test_plan_job', sa.Column('state', sa.VARCHAR(length=100), nullable=True))
    op.add_column('auto_test_plan_job', sa.Column('success_count', sa.Integer(), nullable=True))
    op.add_column('auto_test_plan_job', sa.Column('test_plan_result', sa.Boolean(), nullable=True))
    op.add_column('auto_test_plan_job_detail', sa.Column('api_id', sa.Integer(), nullable=True))
    op.add_column('auto_test_plan_job_detail', sa.Column('api_result', sa.VARCHAR(length=100), nullable=True))
    op.add_column('auto_test_plan_job_detail', sa.Column('response_body', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auto_test_plan_job_detail', 'response_body')
    op.drop_column('auto_test_plan_job_detail', 'api_result')
    op.drop_column('auto_test_plan_job_detail', 'api_id')
    op.drop_column('auto_test_plan_job', 'test_plan_result')
    op.drop_column('auto_test_plan_job', 'success_count')
    op.drop_column('auto_test_plan_job', 'state')
    op.drop_column('auto_test_plan_job', 'fail_count')
    # ### end Alembic commands ###
