"""test_plan_job test_plan_job_detail1

Revision ID: aa48ec131db1
Revises: 36f4b004bd1c
Create Date: 2021-02-05 16:55:23.395805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa48ec131db1'
down_revision = '36f4b004bd1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_test_plan_job',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('test_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_plan_id'], ['auto_test_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_test_plan_job_id'), 'auto_test_plan_job', ['id'], unique=False)
    op.create_table('auto_test_plan_job_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.Column('is_delete', sa.Integer(), server_default='0', nullable=True, comment='逻辑删除:0=未删除,1=删除'),
    sa.Column('test_plan_job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['test_plan_job_id'], ['auto_test_plan_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_test_plan_job_detail_id'), 'auto_test_plan_job_detail', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auto_test_plan_job_detail_id'), table_name='auto_test_plan_job_detail')
    op.drop_table('auto_test_plan_job_detail')
    op.drop_index(op.f('ix_auto_test_plan_job_id'), table_name='auto_test_plan_job')
    op.drop_table('auto_test_plan_job')
    # ### end Alembic commands ###
